fix warnings: include string.h, int type compare, json non-const
need to include string.h for strdup()

otherwise, build with --std=c99 results in:

    reader.c:144:18: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]
         rdr->topic = strdup(topic);
                      ^
    reader.c:144:16: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         rdr->topic = strdup(topic);
                    ^

fix int-type-compare warnings, example:

    command.c:46:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (int i = 0; i < psize; i++) {
                               ^
also:

    command.c:10:1: warning: ‘static’ is not at beginning of declaration [-Wold-style-declaration]
     const static int MAX_BUF_SIZE = 128;
     ^

also, " " and "\n" are single well-known chars, used in one place,
not really deserving of a define at the top.

remove const qualifier from json adapter functions,
with json-c 0.12.1 on ubuntu 18.04 they don't really work:

    json.c:43:37: warning: passing argument 1 of ‘json_object_array_length’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         return json_object_array_length(array);

    json.c:80:32: warning: passing argument 1 of ‘json_object_get_int’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         return json_object_get_int(jsobj);